decision_tree_templates = {
    "Decision Trees": {
        "subtopics": {
            "Introduction": {
                "easy": [
                    "What is the core idea of {topic} in {application}?",
                    "How does {topic} differ from {model} in terms of {aspect}?",
                    "Based on the scatter plot below with {n} points, would {topic} work well? Why?",
                    "Why is {topic} useful for {scenario} in {field}?",
                    "In the line graph below of splits, what does the trend suggest?",
                    "What advantage does {topic} have over {alternative} for {task}?",
                    "Given the data table below with {m} samples, is {topic} suitable? Why?",
                    "How does {topic} classify {output} in a {context} scenario?",
                    "Based on the scatter plot below, why is {topic} a good fit for {application}?",
                    "What’s the main structure of {topic}?",
                    "In the data table below, how does {topic} use {feature} patterns?",
                    "Why might {topic} be chosen for {goal} over {model}?",
                    "Based on the line graph below, what shows {topic}’s strength?",
                    "How does {topic} simplify {task} in {scenario}?"
                ],
                "medium": [
                    "Compare {topic} and {model} for {task} based on {dimension}.",
                    "Based on the scatter plot below with {n} points, why prefer {topic}?",
                    "In the line graph below with slope {s}, why is {topic} effective for {goal}?",
                    "Given the data table below with {m} samples, how does {topic} split {feature}?",
                    "Why does {topic} perform well in {scenario} compared to {alternative}?",
                    "If the scatter plot below shows {n} points, how does {topic} build its structure?",
                    "Based on the line graph below, what does the depth trend imply?",
                    "In a {application} context, why does {topic} fit the data table below?",
                    "Contrast {topic} and {alternative} for {task} using the scatter plot below.",
                    "Given the data table below, why is {topic} ideal for {output} prediction?",
                    "How does {topic} balance {dimension} and {aspect} in {scenario}?",
                    "Based on the scatter plot below, why is {topic} suited for {field}?",
                    "In the line graph below, what does the split trend suggest?",
                    "Why might {topic} struggle with {problem} in the data table below?"
                ],
                "hard": [
                    "Analyze why {topic} outperforms {alternative} for {goal} in {context}.",
                    "Based on the scatter plot below with depth {t}, why is {topic}’s approach effective?",
                    "Critique {topic} versus {model} for {problem} using the line graph below.",
                    "In the data table below with {m} samples, why prefer {topic} over {alternative}?",
                    "Given the scatter plot below, explain {topic}’s suitability for {task}.",
                    "If the line graph below shows noise {p}, how does {topic} adjust?",
                    "Analyze the data table below: how does {topic} handle {feature} complexity?",
                    "Based on the scatter plot below with {n} points, critique {topic}’s splits.",
                    "In the line graph below over {t} levels, what indicates {topic}’s performance?",
                    "Why does {topic} excel in {scenario} but struggle with {problem} in the data below?",
                    "Given the scatter plot below, prove {topic}’s effectiveness for {field}.",
                    "How does {topic} mitigate {noise} in the data table below?",
                    "Critique {topic}’s tree structure based on the line graph below.",
                    "Based on the data table below, justify {topic}’s use in {application}."
                ]
            },
            "Splitting Criteria": {
                "easy": [
                    "What is the purpose of splitting criteria in {topic}?",
                    "How does {topic} calculate Gini impurity?",
                    "Based on the scatter plot below, how does {topic} split {n} points?",
                    "What’s the role of entropy in {topic} for {task}?",
                    "In the line graph below, what does the impurity curve show?",
                    "Given the data table below, how does {topic} choose splits?",
                    "How does information gain work in {topic}?",
                    "Based on the scatter plot below with {n} points, why use Gini?",
                    "In the data table below with {m} samples, what’s the simplest criterion?",
                    "What’s the goal of splitting in {topic}’s {context}?",
                    "Given the line graph below, how does {topic} reduce impurity?",
                    "How does {topic} apply entropy to {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need criteria?",
                    "What does Gini impurity measure in {topic}?"
                ],
                "medium": [
                    "Derive the Gini impurity for {f} classes in {topic}.",
                    "Based on the scatter plot below with {n} points, how does {topic} use entropy?",
                    "In the line graph below, how does {topic} compare Gini and entropy?",
                    "Given the data table below with {m} samples, calculate {topic}’s information gain.",
                    "How does {topic} choose between Gini and entropy for {scenario}?",
                    "Based on the scatter plot below, why does {topic} prefer a specific criterion?",
                    "In the data table below, derive {topic}’s split for {feature}.",
                    "Calculate the entropy reduction for a split in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with criteria?",
                    "How does {topic} use information gain in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {goal} with Gini?",
                    "In the line graph below with slope {s}, what does the criterion imply?",
                    "Given the scatter plot below, how does {topic} adjust splits?",
                    "Why does {topic} rely on impurity in the data table below?"
                ],
                "hard": [
                    "Prove why Gini impurity optimizes {topic}’s {task}.",
                    "Analyze {topic}’s splitting criteria in the scatter plot below with {n} points.",
                    "Derive the full information gain formula for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with entropy?",
                    "Critique Gini versus entropy in {topic} using the line graph below.",
                    "Prove the criterion’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s optimal split criterion.",
                    "In the line graph below, how does {topic} adapt criteria for {task}?",
                    "Analyze {topic}’s sensitivity to impurity in the scatter plot below.",
                    "Prove why {topic} excels with information gain in the data table below.",
                    "Given the line graph below, critique {topic}’s criterion for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with Gini?",
                    "Derive {topic}’s split optimization in the data table below.",
                    "Critique {topic}’s splitting trade-offs in the line graph below."
                ]
            },
            "Tree Construction": {
                "easy": [
                    "What is the main step in {topic}’s construction?",
                    "How does {topic} recursively split data?",
                    "Based on the scatter plot below, how does {topic} build a tree for {n} points?",
                    "What’s the role of stopping conditions in {topic}?",
                    "In the line graph below, what does the depth trend show?",
                    "Given the data table below, how does {topic} grow its tree?",
                    "How does {topic} decide when to stop splitting?",
                    "Based on the scatter plot below with {n} points, why build a tree?",
                    "In the data table below with {m} samples, what’s the construction process?",
                    "What’s the simplest explanation of {topic}’s growth?",
                    "Given the line graph below, how does {topic} form branches?",
                    "How does {topic} split {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need construction?",
                    "What does recursive splitting mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how {topic} constructs a tree for {n} points in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} set depth?",
                    "In the line graph below, how does {topic} apply stopping conditions?",
                    "Given the data table below with {m} samples, how does {topic} split recursively?",
                    "How does {topic} balance depth and splits for {f} features?",
                    "Based on the scatter plot below, why does {topic} stop at a certain depth?",
                    "In the data table below, derive {topic}’s tree structure for {feature}.",
                    "Calculate the number of splits for depth {t} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} in construction?",
                    "How does {topic} grow branches in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {goal} with recursion?",
                    "In the line graph below with slope {s}, what does construction imply?",
                    "Given the scatter plot below, how does {topic} adjust tree growth?",
                    "Why does {topic} use recursion in the data table below?"
                ],
                "hard": [
                    "Prove why recursive splitting works for {topic}’s {task}.",
                    "Analyze {topic}’s construction in the scatter plot below with {n} points.",
                    "Derive the full tree-building process for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} in growth?",
                    "Critique depth versus splits in {topic} using the line graph below.",
                    "Prove the stopping condition’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s optimal tree structure.",
                    "In the line graph below, how does {topic} adapt construction for {task}?",
                    "Analyze {topic}’s computational cost in the scatter plot below.",
                    "Prove why {topic} excels with recursion in the data table below.",
                    "Given the line graph below, critique {topic}’s growth for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} in construction?",
                    "Derive {topic}’s stopping criteria in the data table below.",
                    "Critique {topic}’s construction efficiency in the line graph below."
                ]
            },
            "Pruning": {
                "easy": [
                    "What is the purpose of pruning in {topic}?",
                    "How does {topic} perform pre-pruning?",
                    "Based on the scatter plot below, how does pruning affect {topic}?",
                    "What’s the role of post-pruning in {topic} for {task}?",
                    "In the line graph below, what does the pruned trend show?",
                    "Given the data table below, how does {topic} reduce overfitting?",
                    "How does pre-pruning differ from post-pruning in {topic}?",
                    "Based on the scatter plot below with {n} points, why use pruning?",
                    "In the data table below with {m} samples, what’s pruning’s effect?",
                    "What’s the simplest way to prune in {topic}?",
                    "Given the line graph below, how does {topic} simplify its tree?",
                    "How does {topic} prune {feature} splits in the scatter plot below?",
                    "Based on the data table below, why does {topic} need pruning?",
                    "What does pruning prevent in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how pre-pruning improves {topic}’s accuracy in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} use post-pruning?",
                    "In the line graph below, how does {topic} adjust with pruning?",
                    "Given the data table below with {m} samples, how does {topic} prune {feature}?",
                    "How does {topic} balance pruning and accuracy for {scenario}?",
                    "Based on the scatter plot below, why does {topic} need pruning for {problem}?",
                    "In the data table below, derive {topic}’s pruned structure for {feature}.",
                    "Calculate the pruned depth for a tree in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with pruning?",
                    "How does {topic} apply post-pruning in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with pruning?",
                    "In the line graph below with slope {s}, what does pruning imply?",
                    "Given the scatter plot below, how does {topic} adjust pruning?",
                    "Why does {topic} rely on pruning in the data table below?"
                ],
                "hard": [
                    "Prove why pruning reduces overfitting in {topic}’s {task}.",
                    "Analyze {topic}’s pruning in the scatter plot below with {n} points.",
                    "Derive the full pruning process for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with pruning?",
                    "Critique pre-pruning versus post-pruning in {topic} using the line graph below.",
                    "Prove pruning’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s optimal pruned tree.",
                    "In the line graph below, how does {topic} adapt pruning for {task}?",
                    "Analyze {topic}’s pruning impact in the scatter plot below.",
                    "Prove why {topic} excels with pruning in the data table below.",
                    "Given the line graph below, critique {topic}’s pruning for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with pruning?",
                    "Derive {topic}’s pruning criteria in the data table below.",
                    "Critique {topic}’s pruning trade-offs in the line graph below."
                ]
            },
            "Prediction": {
                "easy": [
                    "How does {topic} predict {output}?",
                    "What’s the role of leaf nodes in {topic}?",
                    "Based on the scatter plot below, how does {topic} classify {n} points?",
                    "What’s the simplest prediction method in {topic}?",
                    "In the line graph below, what does the prediction trend show?",
                    "Given the data table below, how does {topic} assign {output}?",
                    "How does {topic} use leaf nodes for {task}?",
                    "Based on the scatter plot below with {n} points, why predict with leaves?",
                    "In the data table below with {m} samples, what’s the prediction process?",
                    "What’s the goal of prediction in {topic}’s {context}?",
                    "Given the line graph below, how does {topic} reach a decision?",
                    "How does {topic} predict {feature} outcomes in the scatter plot below?",
                    "Based on the data table below, why does {topic} use leaves?",
                    "What does a leaf node represent in {topic}?"
                ],
                "medium": [
                    "Explain how {topic} predicts {output} for {n} points in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} use leaf nodes?",
                    "In the line graph below, how does {topic} assign predictions?",
                    "Given the data table below with {m} samples, how does {topic} classify {feature}?",
                    "How does {topic} handle regression versus classification for {f} features?",
                    "Based on the scatter plot below, why does {topic} rely on leaf predictions?",
                    "In the data table below, derive {topic}’s prediction for {feature}.",
                    "Calculate the prediction value for a leaf in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} in predictions?",
                    "How does {topic} use majority voting in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {goal} with leaves?",
                    "In the line graph below with slope {s}, what does prediction imply?",
                    "Given the scatter plot below, how does {topic} adjust predictions?",
                    "Why does {topic} predict with leaves in the data table below?"
                ],
                "hard": [
                    "Prove why leaf nodes optimize {topic}’s {task}.",
                    "Analyze {topic}’s prediction in the scatter plot below with {n} points.",
                    "Derive the full prediction process for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} in predictions?",
                    "Critique classification versus regression in {topic} using the line graph below.",
                    "Prove the prediction’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s leaf-based decision.",
                    "In the line graph below, how does {topic} adapt predictions for {task}?",
                    "Analyze {topic}’s prediction accuracy in the scatter plot below.",
                    "Prove why {topic} excels with leaf nodes in the data table below.",
                    "Given the line graph below, critique {topic}’s prediction for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} in predictions?",
                    "Derive {topic}’s prediction rule in the data table below.",
                    "Critique {topic}’s prediction efficiency in the line graph below."
                ]
            },
            "Implementation": {
                "easy": [
                    "What Python library is used to implement {topic}?",
                    "How does {topic}’s fit method work in {context}?",
                    "Based on the scatter plot below, how does {topic} predict {n} points?",
                    "Calculate the prediction for a tree in {topic}.",
                    "In the line graph below, what does {topic}’s split represent?",
                    "Given the data table below with {m} samples, how does {topic} train?",
                    "What’s the role of scikit-learn in {topic}’s {task}?",
                    "Based on the scatter plot below, why does {topic} classify easily?",
                    "In the data table below, how does {topic} use {feature} for prediction?",
                    "How does {topic} build a tree in {scenario}?",
                    "Given the line graph below, what does {topic}’s curve predict?",
                    "What’s the simplest way to implement {topic} for {n} points?",
                    "Based on the scatter plot below, how does {topic} handle {output}?",
                    "How does {topic} process {input} in the data table below?"
                ],
                "medium": [
                    "Explain how scikit-learn trains {topic} for {n} samples in the scatter plot below.",
                    "If depth={t}, compute the splits for {topic}.",
                    "Based on the line graph below, how does {topic} predict outcomes?",
                    "Given the data table below with {m} samples, how does {topic} fit the data?",
                    "In the scatter plot below, how does {topic}’s predict method work for {n} points?",
                    "Derive {topic}’s tree structure for {f} features in the data table below.",
                    "Based on the line graph below, why does {topic}’s depth stabilize?",
                    "Given the scatter plot below, how does {topic} handle {feature} in {scenario}?",
                    "In the data table below, how does {topic} compute {output} with splits?",
                    "How does {topic}’s max_depth parameter work in {context}?",
                    "Based on the line graph below with slope {s}, what does {topic} predict?",
                    "Given the scatter plot below, why is {topic} efficient for {task}?",
                    "In the data table below, how does {topic} adjust {parameter}?",
                    "How does {topic} implement {method} in the scatter plot below?"
                ],
                "hard": [
                    "Prove how scikit-learn optimizes {topic}’s {parameter} in {t} levels.",
                    "Analyze {topic}’s runtime for {n} samples in the scatter plot below.",
                    "Derive the full tree equation for {topic} in the data table below.",
                    "In the line graph below, critique {topic}’s implementation for {scenario}.",
                    "Based on the scatter plot below, how does {topic} scale with {f} features?",
                    "Given the data table below with {m} samples, prove {topic}’s efficiency.",
                    "Critique manual versus scikit-learn implementation of {topic} in the line graph below.",
                    "In the scatter plot below with {n} points, how does {topic} handle {noise}?",
                    "Derive {topic}’s split computation for {n} points in the data table below.",
                    "Based on the line graph below, analyze {topic}’s convergence for {task}.",
                    "Prove {topic}’s prediction accuracy in the scatter plot below.",
                    "Given the data table below, how does {topic} optimize {feature} splits?",
                    "Critique {topic}’s implementation trade-offs in the line graph below.",
                    "Analyze {topic}’s performance for {problem} in the data table below."
                ]
            }
        }
    }
}