knn_templates = {
    "k-Nearest Neighbors": {
        "subtopics": {
            "Introduction": {
                "easy": [
                    "What is the basic idea of {topic} in {application}?",
                    "How does {topic} differ from {model} in terms of {aspect}?",
                    "Based on the scatter plot below with {n} points, would {topic} work well? Why?",
                    "Why is {topic} useful for {scenario} in {field}?",
                    "In the line graph below of distances, what does the trend suggest?",
                    "What advantage does {topic} have over {alternative} for {task}?",
                    "Given the data table below with {m} samples, is {topic} suitable? Why?",
                    "How does {topic} classify {output} in a {context} scenario?",
                    "Based on the scatter plot below, why is {topic} a good fit for {application}?",
                    "What’s the main principle behind {topic}’s predictions?",
                    "In the data table below, how does {topic} use {feature} patterns?",
                    "Why might {topic} be chosen for {goal} over {model}?",
                    "Based on the line graph below, what shows {topic}’s strength?",
                    "How does {topic} simplify {task} in {scenario}?"
                ],
                "medium": [
                    "Compare {topic} and {model} for {task} based on {dimension}.",
                    "Based on the scatter plot below with {n} points, why prefer {topic}?",
                    "In the line graph below with slope {s}, why is {topic} effective for {goal}?",
                    "Given the data table below with {m} samples, how does {topic} classify {feature}?",
                    "Why does {topic} perform well in {scenario} compared to {alternative}?",
                    "If the scatter plot below shows {n} points, how does {topic} predict them?",
                    "Based on the line graph below, what does the distance trend imply?",
                    "In a {application} context, why does {topic} fit the data table below?",
                    "Contrast {topic} and {alternative} for {task} using the scatter plot below.",
                    "Given the data table below, why is {topic} ideal for {output} prediction?",
                    "How does {topic} balance {dimension} and {aspect} in {scenario}?",
                    "Based on the scatter plot below, why is {topic} suited for {field}?",
                    "In the line graph below, what does the neighbor distance suggest?",
                    "Why might {topic} struggle with {problem} in the data table below?"
                ],
                "hard": [
                    "Analyze why {topic} outperforms {alternative} for {goal} in {context}.",
                    "Based on the scatter plot below with k={k}, why is {topic}’s approach effective?",
                    "Critique {topic} versus {model} for {problem} using the line graph below.",
                    "In the data table below with {m} samples, why prefer {topic} over {alternative}?",
                    "Given the scatter plot below, explain {topic}’s suitability for {task}.",
                    "If the line graph below shows noise {p}, how does {topic} adjust?",
                    "Analyze the data table below: how does {topic} handle {feature} variance?",
                    "Based on the scatter plot below with {n} points, critique {topic}’s performance.",
                    "In the line graph below over {t} neighbors, what indicates {topic}’s accuracy?",
                    "Why does {topic} excel in {scenario} but struggle with {problem} in the data below?",
                    "Given the scatter plot below, prove {topic}’s effectiveness for {field}.",
                    "How does {topic} mitigate {noise} in the data table below?",
                    "Critique {topic}’s distance-based approach based on the line graph below.",
                    "Based on the data table below, justify {topic}’s use in {application}."
                ]
            },
            "Distance Metrics": {
                "easy": [
                    "What is the role of distance metrics in {topic}?",
                    "Calculate the Euclidean distance between x1={x}, y1={x} and x2={x}, y2={x} in {topic}.",
                    "Based on the scatter plot below, how does {topic} use distances for {n} points?",
                    "What’s the difference between Euclidean and Manhattan distance in {topic}?",
                    "In the line graph below, what does the distance curve show?",
                    "Given the data table below, how does {topic} measure {feature} distances?",
                    "How does {topic} use Minkowski distance for {task}?",
                    "Based on the scatter plot below with {n} points, why use a distance metric?",
                    "In the data table below with {m} samples, what’s the simplest distance metric?",
                    "What’s the purpose of distance in {topic}’s {context}?",
                    "Given the line graph below, how does {topic} rank neighbors?",
                    "How does {topic} apply distances in the scatter plot below?",
                    "Based on the data table below, why does {topic} need distance metrics?",
                    "What does Manhattan distance mean for {topic}?"
                ],
                "medium": [
                    "Derive the Manhattan distance for {f} features in {topic}.",
                    "Based on the scatter plot below with {n} points, how does {topic} use Euclidean distance?",
                    "In the line graph below, how does {topic} compare distance metrics?",
                    "Given the data table below with {m} samples, calculate {topic}’s Minkowski distance.",
                    "How does {topic} choose between Euclidean and Manhattan for {scenario}?",
                    "Based on the scatter plot below, why does {topic} prefer a specific distance metric?",
                    "In the data table below, derive {topic}’s distance for {feature}.",
                    "Calculate the distance with p={p} for Minkowski in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with distances?",
                    "How does {topic} use Manhattan distance in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {goal} with Euclidean?",
                    "In the line graph below with slope {s}, what does the distance imply?",
                    "Given the scatter plot below, how does {topic} adjust distance metrics?",
                    "Why does {topic} rely on distances in the data table below?"
                ],
                "hard": [
                    "Prove why Euclidean distance works for {topic}’s {task}.",
                    "Analyze {topic}’s distance metrics in the scatter plot below with {n} points.",
                    "Derive the full Minkowski distance formula for {topic} with p={p}.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with distances?",
                    "Critique Euclidean versus Manhattan in {topic} using the line graph below.",
                    "Prove the distance metric’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s optimal distance metric.",
                    "In the line graph below, how does {topic} adapt distances for {task}?",
                    "Analyze {topic}’s sensitivity to distance in the scatter plot below.",
                    "Prove why {topic} excels with Manhattan in the data table below.",
                    "Given the line graph below, critique {topic}’s distance fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with Minkowski?",
                    "Derive {topic}’s distance-based ranking in the data table below.",
                    "Critique {topic}’s distance metric choice in the line graph below."
                ]
            },
            "Choosing k": {
                "easy": [
                    "What is the purpose of choosing k in {topic}?",
                    "How does k={k} affect {topic}’s predictions?",
                    "Based on the scatter plot below, how does k={k} classify {n} points?",
                    "What’s the role of k in {topic} for {task}?",
                    "In the line graph below, what does k’s impact show?",
                    "Given the data table below, how does {topic} pick k?",
                    "How does a small k differ from a large k in {topic}?",
                    "Based on the scatter plot below with {n} points, why use k={k}?",
                    "In the data table below with {m} samples, what’s k’s effect?",
                    "What’s the simplest way to choose k in {topic}?",
                    "Given the line graph below, how does {topic} balance k?",
                    "How does {topic} use k with {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need k?",
                    "What does k represent in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how k={k} changes {topic}’s accuracy in the scatter plot below.",
                    "Based on the scatter plot below with k={k}, how does {topic} classify?",
                    "In the line graph below, how does {topic} adjust with k={k}?",
                    "Given the data table below with {m} samples, how does {topic} optimize k?",
                    "How does {topic} balance bias and variance with k in {scenario}?",
                    "Based on the scatter plot below, why does {topic} need a small k for {problem}?",
                    "In the data table below, derive {topic}’s k selection for {feature}.",
                    "Calculate the error rate for k={k} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with k?",
                    "How does {topic} adjust k in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with k={k}?",
                    "In the line graph below with slope {s}, what does k imply?",
                    "Given the scatter plot below, how does {topic} tune k?",
                    "Why does {topic} use k in the data table below?"
                ],
                "hard": [
                    "Prove why k controls bias-variance in {topic} for {task}.",
                    "Analyze {topic}’s k={k} performance in the scatter plot below with {n} points.",
                    "Derive the optimal k for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with k?",
                    "Critique small versus large k in {topic} using the line graph below.",
                    "Prove k’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s k-based decision rule.",
                    "In the line graph below, how does {topic} adapt k for {task}?",
                    "Analyze {topic}’s k sensitivity in the scatter plot below.",
                    "Prove why {topic} balances errors with k in the data table below.",
                    "Given the line graph below, critique {topic}’s k fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with k={k}?",
                    "Derive {topic}’s k optimization in the data table below.",
                    "Critique {topic}’s k selection trade-offs in the line graph below."
                ]
            },
            "Algorithm Mechanics": {
                "easy": [
                    "What is the main step in {topic}’s algorithm?",
                    "How does {topic} find nearest neighbors?",
                    "Based on the scatter plot below, how does {topic} classify {n} points?",
                    "What’s the role of voting in {topic} for {task}?",
                    "In the line graph below, what does the neighbor trend show?",
                    "Given the data table below, how does {topic} predict {output}?",
                    "How does {topic} use weighted voting?",
                    "Based on the scatter plot below with {n} points, why use neighbors?",
                    "In the data table below with {m} samples, what’s the algorithm’s core?",
                    "What’s the simplest explanation of {topic}’s mechanics?",
                    "Given the line graph below, how does {topic} rank neighbors?",
                    "How does {topic} apply voting in the scatter plot below?",
                    "Based on the data table below, why does {topic} rely on neighbors?",
                    "What does nearest neighbor mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how {topic} finds k={k} neighbors in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} vote?",
                    "In the line graph below, how does {topic} weigh neighbors?",
                    "Given the data table below with {m} samples, how does {topic} classify?",
                    "How does {topic} use distance weighting for {f} features?",
                    "Based on the scatter plot below, why does {topic} rely on voting?",
                    "In the data table below, derive {topic}’s prediction for {feature}.",
                    "Calculate the weighted vote for k={k} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} in voting?",
                    "How does {topic} apply nearest neighbor search in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {goal}?",
                    "In the line graph below with slope {s}, what does voting imply?",
                    "Given the scatter plot below, how does {topic} adjust mechanics?",
                    "Why does {topic} use neighbors in the data table below?"
                ],
                "hard": [
                    "Prove why neighbor voting works for {topic}’s {task}.",
                    "Analyze {topic}’s mechanics in the scatter plot below with {n} points.",
                    "Derive the full voting rule for {topic} with k={k}.",
                    "In the data table below with {m} samples, how does {topic} handle {noise}?",
                    "Critique voting versus weighting in {topic} using the line graph below.",
                    "Prove the neighbor search’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s weighted prediction.",
                    "In the line graph below, how does {topic} adapt mechanics for {task}?",
                    "Analyze {topic}’s computational cost in the scatter plot below.",
                    "Prove why {topic} excels with voting in the data table below.",
                    "Given the line graph below, critique {topic}’s mechanics for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} in voting?",
                    "Derive {topic}’s neighbor-based decision in the data table below.",
                    "Critique {topic}’s algorithm efficiency in the line graph below."
                ]
            },
            "Scaling and Normalization": {
                "easy": [
                    "Why does {topic} need feature scaling?",
                    "How does {topic} normalize {feature} data?",
                    "Based on the scatter plot below, how does scaling affect {topic}?",
                    "What’s the role of standardization in {topic} for {task}?",
                    "In the line graph below, what does normalized data show?",
                    "Given the data table below, how does {topic} scale {feature}?",
                    "How does {topic} handle unscaled data?",
                    "Based on the scatter plot below with {n} points, why use normalization?",
                    "In the data table below with {m} samples, what’s scaling’s effect?",
                    "What’s the simplest way to scale data for {topic}?",
                    "Given the line graph below, how does {topic} adjust for scaling?",
                    "How does {topic} use normalized {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} require scaling?",
                    "What does standardization mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how normalization improves {topic}’s accuracy in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} use scaled data?",
                    "In the line graph below, how does {topic} adjust with standardization?",
                    "Given the data table below with {m} samples, how does {topic} normalize {feature}?",
                    "How does {topic} handle feature ranges for {f} features?",
                    "Based on the scatter plot below, why does {topic} need scaling for {problem}?",
                    "In the data table below, derive {topic}’s scaled prediction.",
                    "Calculate the normalized value for x={x} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with scaling?",
                    "How does {topic} apply standardization in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with normalization?",
                    "In the line graph below with slope {s}, what does scaling imply?",
                    "Given the scatter plot below, how does {topic} adjust unscaled data?",
                    "Why does {topic} rely on scaling in the data table below?"
                ],
                "hard": [
                    "Prove why scaling is critical for {topic}’s {task}.",
                    "Analyze {topic}’s performance with unscaled data in the scatter plot below.",
                    "Derive the standardization formula for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with scaling?",
                    "Critique scaling versus no scaling in {topic} using the line graph below.",
                    "Prove normalization’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s scaled distance rule.",
                    "In the line graph below, how does {topic} adapt scaling for {task}?",
                    "Analyze {topic}’s sensitivity to scale in the scatter plot below.",
                    "Prove why {topic} excels with normalized data in the data table below.",
                    "Given the line graph below, critique {topic}’s scaling for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} ranges?",
                    "Derive {topic}’s normalization impact in the data table below.",
                    "Critique {topic}’s scaling trade-offs in the line graph below."
                ]
            },
            "Implementation": {
                "easy": [
                    "What Python library is used to implement {topic}?",
                    "How does {topic}’s fit method work in {context}?",
                    "Based on the scatter plot below, how does {topic} predict {n} points?",
                    "Calculate the prediction for k={k}, x={x} in {topic}.",
                    "In the line graph below, what does {topic}’s distance represent?",
                    "Given the data table below with {m} samples, how does {topic} train?",
                    "What’s the role of scikit-learn in {topic}’s {task}?",
                    "Based on the scatter plot below, why does {topic} classify easily?",
                    "In the data table below, how does {topic} use {feature} for prediction?",
                    "How does {topic} compute distances in {scenario}?",
                    "Given the line graph below, what does {topic}’s curve predict?",
                    "What’s the simplest way to implement {topic} for {n} points?",
                    "Based on the scatter plot below, how does {topic} handle {output}?",
                    "How does {topic} process {input} in the data table below?"
                ],
                "medium": [
                    "Explain how scikit-learn trains {topic} for {n} samples in the scatter plot below.",
                    "If k={k}, compute the output for x={x} in {topic}.",
                    "Based on the line graph below, how does {topic} predict neighbors?",
                    "Given the data table below with {m} samples, how does {topic} fit the data?",
                    "In the scatter plot below, how does {topic}’s predict method work for {n} points?",
                    "Derive {topic}’s prediction rule for {f} features in the data table below.",
                    "Based on the line graph below, why does {topic}’s distance stabilize?",
                    "Given the scatter plot below, how does {topic} handle {feature} in {scenario}?",
                    "In the data table below, how does {topic} compute {output} with k={k}?",
                    "How does {topic}’s kneighbors method work for k={k} in {context}?",
                    "Based on the line graph below with slope {s}, what does {topic} predict?",
                    "Given the scatter plot below, why is {topic} efficient for {task}?",
                    "In the data table below, how does {topic} adjust {parameter}?",
                    "How does {topic} implement {method} in the scatter plot below?"
                ],
                "hard": [
                    "Prove how scikit-learn optimizes {topic}’s {parameter} in {t} iterations.",
                    "Analyze {topic}’s runtime for {n} samples in the scatter plot below.",
                    "Derive the full prediction equation for {topic} with k={k} in the data table below.",
                    "In the line graph below, critique {topic}’s implementation for {scenario}.",
                    "Based on the scatter plot below, how does {topic} scale with {f} features?",
                    "Given the data table below with {m} samples, prove {topic}’s efficiency.",
                    "Critique manual versus scikit-learn implementation of {topic} in the line graph below.",
                    "In the scatter plot below with {n} points, how does {topic} handle {noise}?",
                    "Derive {topic}’s distance computation for {n} points in the data table below.",
                    "Based on the line graph below, analyze {topic}’s convergence for {task}.",
                    "Prove {topic}’s prediction accuracy in the scatter plot below with k={k}.",
                    "Given the data table below, how does {topic} optimize {feature} distances?",
                    "Critique {topic}’s implementation trade-offs in the line graph below.",
                    "Analyze {topic}’s performance for {problem} in the data table below."
                ]
            }
        }
    }
}