logistic_regression_templates = {
    "Logistic Regression": {
        "subtopics": {
            "Introduction": {
                "easy": [
                    "What is the main goal of {topic} in {application}?",
                    "How does {topic} differ from {model} in terms of {aspect}?",
                    "Based on the scatter plot below with {n} points, would {topic} be effective? Why?",
                    "Why is {topic} commonly used for {scenario} in {field}?",
                    "In the line graph below of probability outputs, what does the curve indicate?",
                    "What advantage does {topic} have over {alternative} for {task}?",
                    "Given the data table below with {m} samples, is {topic} suitable? Why?",
                    "How does {topic} predict {output} in a {context} scenario?",
                    "Based on the scatter plot below, why is {topic} a good fit for {application}?",
                    "What’s one practical use of {topic} in {field}?",
                    "In the data table below, how does {topic} interpret {feature} patterns?",
                    "Why might {topic} be preferred for {goal} over {model}?",
                    "Based on the line graph below, what trend suggests {topic} works well?",
                    "How does {topic} simplify {task} in {scenario}?"
                ],
                "medium": [
                    "Compare {topic} and {model} for {task} based on {dimension}.",
                    "Based on the scatter plot below with {n} points, why choose {topic}?",
                    "In the line graph below with slope {s}, why is {topic} effective for {goal}?",
                    "Given the data table below with {m} samples, how does {topic} handle {feature}?",
                    "Why does {topic} perform well in {scenario} compared to {alternative}?",
                    "If the scatter plot below shows {n} points, how does {topic} classify them?",
                    "Based on the line graph below, what does the cost trend imply for {topic}?",
                    "In a {application} context, why does {topic} fit the data table below?",
                    "Contrast {topic} and {alternative} for {task} using the scatter plot below.",
                    "Given the data table below, why is {topic} ideal for {output} prediction?",
                    "How does {topic} balance {dimension} and {aspect} in {scenario}?",
                    "Based on the scatter plot below, why is {topic} suited for {field}?",
                    "In the line graph below, what does the probability curve suggest about {topic}?",
                    "Why might {topic} face challenges with {problem} in the data table below?"
                ],
                "hard": [
                    "Analyze why {topic} outperforms {alternative} for {goal} in {context}.",
                    "Based on the scatter plot below with w={w}, why is {topic}’s approach optimal?",
                    "Critique {topic} versus {model} for {problem} using the line graph below.",
                    "In the data table below with {m} samples, why prefer {topic} over {alternative}?",
                    "Given the scatter plot below, explain {topic}’s suitability for {task}.",
                    "If the line graph below shows noise {p}, how does {topic} adjust?",
                    "Analyze the data table below: how does {topic} handle {feature} variance?",
                    "Based on the scatter plot below with {n} points, critique {topic}’s performance.",
                    "In the line graph below over {t} iterations, what indicates {topic}’s convergence?",
                    "Why does {topic} excel in {scenario} but struggle with {problem} in the data below?",
                    "Given the scatter plot below, prove {topic}’s effectiveness for {field}.",
                    "How does {topic} mitigate {noise} in the data table below?",
                    "Critique {topic}’s assumptions for {task} based on the line graph below.",
                    "Based on the data table below, justify {topic}’s use in {application}."
                ]
            },
            "Mathematical Foundation": {
                "easy": [
                    "What is the sigmoid function in {topic} and its purpose for {task}?",
                    "Compute the sigmoid output for x={x} in {topic}.",
                    "Based on the scatter plot below, what does the decision boundary do?",
                    "If P(y=0) = {p}, what’s P(y=1) in {topic}?",
                    "In the line graph below, what’s the range of the sigmoid output?",
                    "Given the data table below, how does {topic} assign probabilities?",
                    "Calculate the logit if the probability is {p} in {topic}.",
                    "Based on the scatter plot below, how does the boundary separate classes?",
                    "In the line graph below at x={x}, what does the sigmoid slope mean?",
                    "How does {topic} use {input} to generate probabilities?",
                    "Given the data table below with {m} samples, what’s {topic}’s decision rule?",
                    "What’s the role of the decision boundary in {topic} for {n} features?",
                    "Based on the line graph below, why does the sigmoid fit {task}?",
                    "How are weights used in {topic} based on the scatter plot below?"
                ],
                "medium": [
                    "Derive the sigmoid output for x={x} in {topic} step-by-step.",
                    "Based on the scatter plot below with w={w}, how does the boundary function?",
                    "If logit is {l}, calculate the probability in {topic}.",
                    "In the line graph below, how does the sigmoid ensure outputs between {a} and {b}?",
                    "Compute the sigmoid’s derivative at x={x} in {topic}.",
                    "Given the data table below, how does {topic} use w={w} to predict {output}?",
                    "Based on the scatter plot below, why does the boundary shift with w={w}?",
                    "In the line graph below, how steep is the sigmoid at x={x}?",
                    "Given the data table below with {m} samples, derive {topic}’s probability rule.",
                    "How does {topic} handle {noise} in the scatter plot below?",
                    "Calculate the decision threshold for P(y=1)={p} in {topic}.",
                    "Based on the line graph below with slope {s}, what does it imply for {task}?",
                    "In the scatter plot below with w={w}, justify the boundary’s placement.",
                    "Given the data table below, how does {topic} adjust for {feature} spread?"
                ],
                "hard": [
                    "Prove the sigmoid’s optimality for {topic}’s {task} using {theory}.",
                    "Derive the {n}-dimensional boundary equation for {topic} from the scatter plot below.",
                    "Analyze {topic}’s robustness to {noise} in the data table below.",
                    "If w={w}, b={b}, compute the margin width in the scatter plot below.",
                    "Critique the sigmoid versus {alternative} based on the line graph below.",
                    "Derive the sigmoid’s second derivative at x={x} in {topic}.",
                    "Prove {topic}’s outputs stay between {a} and {b} in the line graph below.",
                    "In the data table below with {m} samples, how does {topic} manage {noise}?",
                    "If logit={l}, derive the inverse mapping in the scatter plot below.",
                    "Analyze how {n} features affect the boundary in the scatter plot below.",
                    "Prove the sigmoid’s convexity for {topic}’s {goal} using the line graph below.",
                    "Based on the data table below, why does the sigmoid suit {task}?",
                    "How does {topic} adapt to {problem} in the scatter plot below?",
                    "Critique {topic}’s linearity in the data table below with {n} features."
                ]
            },
            "Cost Function and Optimization": {
                "easy": [
                    "What is the cost function in {topic} and its purpose?",
                    "Calculate the log loss for y={y}, p={p} in {topic}.",
                    "Based on the line graph below, what does the cost trend show?",
                    "How does {topic} use gradient descent for {task}?",
                    "Given the data table below, why does {topic} minimize errors?",
                    "What’s the role of log loss in {topic} for {output}?",
                    "In the line graph below over {t} iterations, what’s the cost’s behavior?",
                    "How does {topic} adjust weights based on the data table below?",
                    "Based on the scatter plot below, why does {topic} optimize the boundary?",
                    "What’s the simplest explanation of gradient descent in {topic}?",
                    "Given the data table below with {m} samples, how does {topic} reduce cost?",
                    "In the line graph below, why does the cost decrease?",
                    "How does {topic} measure error for {n} points in the scatter plot below?",
                    "What does the cost function penalize in {topic}?"
                ],
                "medium": [
                    "Derive the log loss formula for y={y}, p={p} in {topic}.",
                    "Based on the line graph below, how does gradient descent affect {topic}’s cost?",
                    "Given the data table below with {m} samples, how does {topic} optimize weights?",
                    "If weight w={w} updates by {d}, what’s the new weight in {topic}?",
                    "In the scatter plot below, how does {topic} minimize errors for {n} points?",
                    "Compute the gradient of log loss for y={y}, p={p} in {topic}.",
                    "Based on the line graph below over {t} iterations, why does cost drop?",
                    "Given the data table below, how does {topic} adjust for {feature} errors?",
                    "How does gradient descent update {topic}’s {parameter} in {scenario}?",
                    "In the scatter plot below with w={w}, why does optimization shift the boundary?",
                    "Calculate the cost change with learning rate {r} in {topic}.",
                    "Based on the line graph below, what does a flat cost imply?",
                    "Given the data table below, how does {topic} handle {noise} in optimization?",
                    "Why does {topic}’s cost converge in the line graph below?"
                ],
                "hard": [
                    "Prove why log loss is convex for {topic}’s optimization.",
                    "Analyze the impact of learning rate {r} on {topic}’s convergence in the line graph below.",
                    "Derive the gradient descent update rule for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} optimize under {noise}?",
                    "If cost is {c} for {n} points in the scatter plot below, estimate the final cost.",
                    "Critique gradient descent versus {alternative} in {topic} based on the line graph below.",
                    "Prove the convergence of {topic}’s cost in {t} steps using the data table below.",
                    "Based on the scatter plot below, how does {topic} balance cost and boundary fit?",
                    "Derive the full optimization process for {topic} with w={w}, b={b}.",
                    "In the line graph below, why does {topic}’s cost stabilize at {c}?",
                    "Analyze how {topic} handles {problem} in the data table below during optimization.",
                    "Prove the effect of {parameter} on {topic}’s cost in the scatter plot below.",
                    "Critique {topic}’s optimization speed based on the line graph below.",
                    "How does {topic} adjust gradients for {feature} in the data table below?"
                ]
            },
            "Regularization": {
                "easy": [
                    "What is the purpose of regularization in {topic}?",
                    "Calculate the L2 penalty for w={w}, lambda={l} in {topic}.",
                    "Based on the scatter plot below, how does regularization affect {topic}?",
                    "What does L1 regularization do to weights in {topic}?",
                    "In the line graph below, how does regularization change the cost?",
                    "Given the data table below, why does {topic} use regularization?",
                    "How does {topic} prevent overfitting with {method}?",
                    "Based on the scatter plot below with {n} points, what’s regularization’s role?",
                    "In the data table below with {m} samples, how does L2 regularization help?",
                    "What’s the difference between L1 and L2 regularization in {topic}?",
                    "Given the line graph below, why does regularization stabilize {topic}?",
                    "How does {topic} adjust weights with lambda={l} in {scenario}?",
                    "Based on the scatter plot below, why does regularization improve {task}?",
                    "What’s the simplest effect of regularization on {topic}?"
                ],
                "medium": [
                    "Derive the L1 regularization term for w={w} in {topic}.",
                    "Based on the scatter plot below, how does regularization shrink weights?",
                    "In the line graph below with lambda={l}, how does {topic}’s cost change?",
                    "Given the data table below with {m} samples, how does L2 regularization work?",
                    "Compare L1 and L2 regularization effects on {topic} for w={w}.",
                    "Based on the scatter plot below with {n} points, why does regularization help?",
                    "In the data table below, how does {topic} balance {feature} with regularization?",
                    "Calculate the regularized cost for loss={c}, w={w}, lambda={l} in {topic}.",
                    "Given the line graph below, how does regularization prevent overfitting?",
                    "How does {topic} adjust the boundary with L1 in the scatter plot below?",
                    "Based on the data table below, why does regularization improve {goal}?",
                    "In the line graph below, what does a high lambda={l} imply for {topic}?",
                    "Given the scatter plot below, how does regularization affect {dimension}?",
                    "Why does {topic} use {method} for {problem} in the data table below?"
                ],
                "hard": [
                    "Prove why L1 regularization induces sparsity in {topic} for {f} features.",
                    "Analyze how regularization impacts {topic}’s fit in the scatter plot below.",
                    "Derive the full cost with L2 regularization for w={w}, lambda={l} in {topic}.",
                    "In the data table below with {m} samples, how does regularization handle {noise}?",
                    "Critique L1 versus L2 regularization in {topic} based on the line graph below.",
                    "Prove the effect of lambda={l} on {topic}’s weights in the scatter plot below.",
                    "Based on the data table below, how does regularization balance {dimension}?",
                    "In the line graph below with lambda={l}, why does {topic} stabilize?",
                    "Analyze {topic}’s boundary shift with regularization in the scatter plot below.",
                    "Derive the gradient of L2 regularization for w={w} in {topic}.",
                    "Given the data table below, critique {topic}’s regularization for {problem}.",
                    "Prove how regularization improves {goal} in the line graph below.",
                    "Based on the scatter plot below, how does {topic} adapt to {feature} with L1?",
                    "Critique {topic}’s regularization trade-offs in the data table below."
                ]
            },
            "Multiclass Logistic Regression": {
                "easy": [
                    "What is the goal of multiclass {topic} in {application}?",
                    "How does OvR work in {topic} for {n} classes?",
                    "Based on the scatter plot below, can {topic} handle {n} classes?",
                    "What’s the difference between OvR and OvO in {topic}?",
                    "In the line graph below, what does the probability curve show for {n} classes?",
                    "Given the data table below with {m} samples, how does {topic} classify {n} classes?",
                    "How does {topic} extend binary classification to {task}?",
                    "Based on the scatter plot below, why use OvR for {n} classes?",
                    "In the data table below, what’s the role of OvO in {topic}?",
                    "Calculate the number of OvR classifiers for {n} classes in {topic}.",
                    "Given the line graph below, how does {topic} predict {n} classes?",
                    "How does {topic} handle {feature} for {n} classes in the scatter plot below?",
                    "Based on the data table below, why does {topic} support {goal}?",
                    "What’s the simplest way {topic} manages {n} classes?"
                ],
                "medium": [
                    "Explain how OvR trains {n} classifiers in {topic}.",
                    "Based on the scatter plot below with {n} classes, why use OvO in {topic}?",
                    "In the line graph below, how does {topic} assign probabilities to {n} classes?",
                    "Given the data table below with {m} samples, how does OvR work in {topic}?",
                    "Compare OvR and OvO in {topic} for {n} classes based on {dimension}.",
                    "Based on the scatter plot below, how does {topic} separate {n} classes?",
                    "In the data table below, derive {topic}’s OvO decision for {n} classes.",
                    "Calculate the number of OvO pairs for {n} classes in {topic}.",
                    "Given the line graph below, how does {topic} handle {feature} for {n} classes?",
                    "How does {topic} adjust its cost for {n} classes in the data table below?",
                    "Based on the scatter plot below, why does OvR suit {scenario}?",
                    "In the line graph below with {n} curves, what does it imply for {topic}?",
                    "Given the data table below, how does {topic} manage {noise} with {n} classes?",
                    "Why does {topic} prefer OvR over OvO in the scatter plot below?"
                ],
                "hard": [
                    "Prove why OvR scales better than OvO in {topic} for {n} classes.",
                    "Analyze the computational cost of OvO in {topic} based on the scatter plot below.",
                    "Derive the decision rule for OvR with {n} classes in the data table below.",
                    "In the line graph below with {n} probabilities, why use {topic} for {task}?",
                    "Critique OvR versus OvO in {topic} for {problem} using the scatter plot below.",
                    "Prove how {topic} handles {n} classes in the data table below with {noise}.",
                    "Based on the scatter plot below, analyze {topic}’s OvO performance for {n} classes.",
                    "In the line graph below, how does {topic} adapt probabilities for {n} classes?",
                    "Derive the full OvR process for {n} classes in {topic} with w={w}.",
                    "Given the data table below, critique {topic}’s multiclass fit for {feature}.",
                    "Prove the efficiency of OvO for {n} classes in the scatter plot below.",
                    "Based on the line graph below, how does {topic} balance {dimension} for {n} classes?",
                    "Analyze {topic}’s multiclass boundary in the scatter plot below with {n} classes.",
                    "Critique {topic}’s OvR approach for {scenario} in the data table below."
                ]
            },
            "Implementation": {
                "easy": [
                    "What Python library is commonly used for {topic}?",
                    "How does {topic}’s fit method work in {context}?",
                    "Based on the scatter plot below, how does {topic} predict {n} points?",
                    "Calculate the prediction for w={w}, x={x} in {topic}.",
                    "In the line graph below, what does {topic}’s output represent?",
                    "Given the data table below with {m} samples, how does {topic} train?",
                    "What’s the role of scikit-learn in {topic}’s {task}?",
                    "Based on the scatter plot below, why does {topic} classify easily?",
                    "In the data table below, how does {topic} use {feature} for prediction?",
                    "How does {topic} compute probabilities in {scenario}?",
                    "Given the line graph below, what does {topic}’s curve predict?",
                    "What’s the simplest way to implement {topic} for {n} points?",
                    "Based on the scatter plot below, how does {topic} handle {output}?",
                    "How does {topic} process {input} in the data table below?"
                ],
                "medium": [
                    "Explain how scikit-learn trains {topic} for {n} samples in the scatter plot below.",
                    "If coefficients are w1={w1}, w2={w2}, compute the output for x1={x}, x2={x} in {topic}.",
                    "Based on the line graph below, how does {topic} predict probabilities?",
                    "Given the data table below with {m} samples, how does {topic} fit the data?",
                    "In the scatter plot below, how does {topic}’s predict method work for {n} points?",
                    "Derive {topic}’s prediction rule for {f} features in the data table below.",
                    "Based on the line graph below, why does {topic}’s output stabilize?",
                    "Given the scatter plot below, how does {topic} handle {feature} in {scenario}?",
                    "In the data table below, how does {topic} compute {output} with w={w}?",
                    "How does {topic}’s predict_proba work for P(y=1)={p} in {context}?",
                    "Based on the line graph below with slope {s}, what does {topic} predict?",
                    "Given the scatter plot below, why is {topic} efficient for {task}?",
                    "In the data table below, how does {topic} adjust {parameter}?",
                    "How does {topic} implement {method} in the scatter plot below?"
                ],
                "hard": [
                    "Prove how scikit-learn optimizes {topic}’s {parameter} in {t} iterations.",
                    "Analyze {topic}’s runtime for {n} samples in the scatter plot below.",
                    "Derive the full prediction equation for {topic} with w={w} in the data table below.",
                    "In the line graph below, critique {topic}’s implementation for {scenario}.",
                    "Based on the scatter plot below, how does {topic} scale with {f} features?",
                    "Given the data table below with {m} samples, prove {topic}’s efficiency.",
                    "Critique manual versus scikit-learn implementation of {topic} in the line graph below.",
                    "In the scatter plot below with {n} points, how does {topic} handle {noise}?",
                    "Derive {topic}’s probability distribution for {n} classes in the data table below.",
                    "Based on the line graph below, analyze {topic}’s convergence for {task}.",
                    "Prove {topic}’s prediction accuracy in the scatter plot below with w={w}.",
                    "Given the data table below, how does {topic} optimize {feature} weights?",
                    "Critique {topic}’s implementation trade-offs in the line graph below.",
                    "Analyze {topic}’s performance for {problem} in the data table below."
                ]
            }
        }
    }
}