naive_bayes_templates = {
    "Naïve Bayes": {
        "subtopics": {
            "Introduction": {
                "easy": [
                    "What is the main idea behind {topic} in {application}?",
                    "How does {topic} differ from {model} in terms of {aspect}?",
                    "Based on the scatter plot below with {n} points, would {topic} work well? Why?",
                    "Why is {topic} effective for {scenario} in {field}?",
                    "In the line graph below of probability outputs, what does the curve suggest?",
                    "What advantage does {topic} have over {alternative} for {task}?",
                    "Given the data table below with {m} samples, is {topic} suitable? Why?",
                    "How does {topic} classify {output} in a {context} scenario?",
                    "Based on the scatter plot below, why is {topic} a good fit for {application}?",
                    "What’s one key assumption of {topic} in {field}?",
                    "In the data table below, how does {topic} use {feature} patterns?",
                    "Why might {topic} be chosen for {goal} over {model}?",
                    "Based on the line graph below, what trend shows {topic}’s strength?",
                    "How does {topic} simplify {task} in {scenario}?"
                ],
                "medium": [
                    "Compare {topic} and {model} for {task} based on {dimension}.",
                    "Based on the scatter plot below with {n} points, why prefer {topic}?",
                    "In the line graph below with slope {s}, why is {topic} effective for {goal}?",
                    "Given the data table below with {m} samples, how does {topic} classify {feature}?",
                    "Why does {topic} perform well in {scenario} compared to {alternative}?",
                    "If the scatter plot below shows {n} points, how does {topic} predict them?",
                    "Based on the line graph below, what does the probability trend imply?",
                    "In a {application} context, why does {topic} fit the data table below?",
                    "Contrast {topic} and {alternative} for {task} using the scatter plot below.",
                    "Given the data table below, why is {topic} ideal for {output} prediction?",
                    "How does {topic} balance {dimension} and {aspect} in {scenario}?",
                    "Based on the scatter plot below, why is {topic} suited for {field}?",
                    "In the line graph below, what does the probability curve suggest about {topic}?",
                    "Why might {topic} struggle with {problem} in the data table below?"
                ],
                "hard": [
                    "Analyze why {topic} outperforms {alternative} for {goal} in {context}.",
                    "Based on the scatter plot below with w={w}, why is {topic}’s approach effective?",
                    "Critique {topic} versus {model} for {problem} using the line graph below.",
                    "In the data table below with {m} samples, why prefer {topic} over {alternative}?",
                    "Given the scatter plot below, explain {topic}’s suitability for {task}.",
                    "If the line graph below shows noise {p}, how does {topic} adjust?",
                    "Analyze the data table below: how does {topic} handle {feature} dependencies?",
                    "Based on the scatter plot below with {n} points, critique {topic}’s assumptions.",
                    "In the line graph below over {t} iterations, what indicates {topic}’s performance?",
                    "Why does {topic} excel in {scenario} but struggle with {problem} in the data below?",
                    "Given the scatter plot below, prove {topic}’s effectiveness for {field}.",
                    "How does {topic} mitigate {noise} in the data table below?",
                    "Critique {topic}’s independence assumption based on the line graph below.",
                    "Based on the data table below, justify {topic}’s use in {application}."
                ]
            },
            "Probability Basics": {
                "easy": [
                    "What is Bayes’ theorem and its role in {topic}?",
                    "Calculate P(A|B) given P(B|A)={p}, P(A)={p}, P(B)={p} in {topic}.",
                    "Based on the scatter plot below, how does {topic} use probabilities?",
                    "What’s the conditional probability in {topic} for {task}?",
                    "In the line graph below, what does the probability curve represent?",
                    "Given the data table below, how does {topic} apply Bayes’ rule?",
                    "How does {topic} compute posterior probabilities?",
                    "Based on the scatter plot below with {n} points, why does {topic} use priors?",
                    "In the data table below with {m} samples, what’s the likelihood’s role?",
                    "What’s the simplest explanation of Bayes’ theorem in {topic}?",
                    "Given the line graph below, how does {topic} estimate {output}?",
                    "How does {topic} use {feature} probabilities in the scatter plot below?",
                    "Based on the data table below, why does {topic} rely on priors?",
                    "What does P(B|A) mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Derive Bayes’ theorem for {topic} with P(A)={p}, P(B)={p}.",
                    "Based on the scatter plot below with {n} points, how does {topic} compute posteriors?",
                    "In the line graph below, how does {topic} update probabilities?",
                    "Given the data table below with {m} samples, calculate {topic}’s likelihood.",
                    "How does {topic} combine priors and likelihoods for {task}?",
                    "Based on the scatter plot below, why does {topic} assume independence?",
                    "In the data table below, derive {topic}’s posterior for {feature}.",
                    "Calculate the joint probability for {f} features in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} in probabilities?",
                    "How does {topic} use Bayes’ rule in the scatter plot below?",
                    "Based on the data table below, why does {topic} prioritize likelihood?",
                    "In the line graph below with slope {s}, what does it imply for {topic}?",
                    "Given the scatter plot below, how does {topic} adjust priors?",
                    "Why does {topic} simplify probabilities in the data table below?"
                ],
                "hard": [
                    "Prove Bayes’ theorem’s correctness for {topic}’s {task}.",
                    "Analyze how {topic} computes posteriors in the scatter plot below.",
                    "Derive the full probability model for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise}?",
                    "Critique {topic}’s independence assumption using the line graph below.",
                    "Prove the likelihood’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s joint probability.",
                    "In the line graph below, how does {topic} balance priors and likelihoods?",
                    "Analyze {topic}’s probability updates for {n} points in the scatter plot below.",
                    "Prove why {topic}’s simplicity works in the data table below.",
                    "Given the line graph below, critique {topic}’s probability model for {problem}.",
                    "Based on the scatter plot below, how does {topic} adapt to {feature}?",
                    "Derive {topic}’s posterior distribution in the data table below.",
                    "Critique {topic}’s Bayes’ application in the line graph below."
                ]
            },
            "Gaussian Naïve Bayes": {
                "easy": [
                    "What is the assumption of {topic} for continuous data?",
                    "Calculate the Gaussian probability for x={x}, mean={m}, std={s} in {topic}.",
                    "Based on the scatter plot below, how does {topic} classify {n} points?",
                    "What’s the role of variance in {topic} for {task}?",
                    "In the line graph below, what does the Gaussian curve show?",
                    "Given the data table below, how does {topic} predict {output}?",
                    "How does {topic} model {feature} distributions?",
                    "Based on the scatter plot below with {n} points, why use {topic}?",
                    "In the data table below with {m} samples, what’s the Gaussian’s role?",
                    "What’s the simplest way {topic} handles continuous {input}?",
                    "Given the line graph below, how does {topic} estimate probabilities?",
                    "How does {topic} use means in the scatter plot below?",
                    "Based on the data table below, why does {topic} assume normality?",
                    "What does the Gaussian assumption mean for {topic} in {context}?"
                ],
                "medium": [
                    "Derive the Gaussian probability for x={x} in {topic} with mean={m}, std={s}.",
                    "Based on the scatter plot below with {n} points, how does {topic} classify?",
                    "In the line graph below, how does {topic} fit Gaussian curves?",
                    "Given the data table below with {m} samples, calculate {topic}’s likelihood.",
                    "How does {topic} estimate variance for {f} features?",
                    "Based on the scatter plot below, why does {topic} suit continuous data?",
                    "In the data table below, derive {topic}’s Gaussian prediction.",
                    "Calculate the probability density for {feature} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} in Gaussians?",
                    "How does {topic} use standard deviation in the scatter plot below?",
                    "Based on the data table below, why does {topic} fit {scenario}?",
                    "In the line graph below with slope {s}, what does it imply for {topic}?",
                    "Given the scatter plot below, how does {topic} adjust means?",
                    "Why does {topic} model {feature} as Gaussian in the data table below?"
                ],
                "hard": [
                    "Prove why Gaussian assumptions work for {topic}’s {task}.",
                    "Analyze {topic}’s classification in the scatter plot below with {n} points.",
                    "Derive the full Gaussian model for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise}?",
                    "Critique {topic}’s normality assumption using the line graph below.",
                    "Prove the Gaussian likelihood’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s probability density.",
                    "In the line graph below, how does {topic} adapt Gaussians for {task}?",
                    "Analyze {topic}’s variance estimation in the scatter plot below.",
                    "Prove why {topic} excels for continuous data in the data table below.",
                    "Given the line graph below, critique {topic}’s Gaussian fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} skewness?",
                    "Derive {topic}’s Gaussian posterior in the data table below.",
                    "Critique {topic}’s Gaussian approach in the line graph below."
                ]
            },
            "Multinomial Naïve Bayes": {
                "easy": [
                    "What is the purpose of {topic} for discrete data?",
                    "Calculate the probability of a count={c} in {topic} with p={p}.",
                    "Based on the scatter plot below, how does {topic} classify {n} points?",
                    "What’s the role of word counts in {topic} for {task}?",
                    "In the line graph below, what does the probability trend show?",
                    "Given the data table below, how does {topic} predict {output}?",
                    "How does {topic} handle {feature} frequencies?",
                    "Based on the scatter plot below with {n} points, why use {topic}?",
                    "In the data table below with {m} samples, what’s {topic}’s assumption?",
                    "What’s the simplest way {topic} processes text data?",
                    "Given the line graph below, how does {topic} estimate likelihoods?",
                    "How does {topic} use counts in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {application}?",
                    "What does {topic} assume about {feature} in {context}?"
                ],
                "medium": [
                    "Derive the multinomial probability for count={c} in {topic} with p={p}.",
                    "Based on the scatter plot below with {n} points, how does {topic} classify?",
                    "In the line graph below, how does {topic} model frequency probabilities?",
                    "Given the data table below with {m} samples, calculate {topic}’s likelihood.",
                    "How does {topic} estimate probabilities for {f} features?",
                    "Based on the scatter plot below, why does {topic} fit discrete data?",
                    "In the data table below, derive {topic}’s prediction for {feature}.",
                    "Calculate the likelihood for {feature} counts in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} in counts?",
                    "How does {topic} use frequencies in the scatter plot below?",
                    "Based on the data table below, why does {topic} excel in {scenario}?",
                    "In the line graph below with slope {s}, what does it imply for {topic}?",
                    "Given the scatter plot below, how does {topic} adjust probabilities?",
                    "Why does {topic} model {feature} as multinomial in the data table below?"
                ],
                "hard": [
                    "Prove why multinomial assumptions work for {topic}’s {task}.",
                    "Analyze {topic}’s classification in the scatter plot below with {n} points.",
                    "Derive the full multinomial model for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise}?",
                    "Critique {topic}’s frequency assumption using the line graph below.",
                    "Prove the likelihood’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s multinomial probability.",
                    "In the line graph below, how does {topic} adapt counts for {task}?",
                    "Analyze {topic}’s frequency estimation in the scatter plot below.",
                    "Prove why {topic} excels for text data in the data table below.",
                    "Given the line graph below, critique {topic}’s multinomial fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} sparsity?",
                    "Derive {topic}’s multinomial posterior in the data table below.",
                    "Critique {topic}’s multinomial approach in the line graph below."
                ]
            },
            "Bernoulli Naïve Bayes": {
                "easy": [
                    "What is the goal of {topic} for binary data?",
                    "Calculate the probability of presence={y} in {topic} with p={p}.",
                    "Based on the scatter plot below, how does {topic} classify {n} points?",
                    "What’s the role of feature presence in {topic} for {task}?",
                    "In the line graph below, what does the probability curve indicate?",
                    "Given the data table below, how does {topic} predict {output}?",
                    "How does {topic} model {feature} occurrences?",
                    "Based on the scatter plot below with {n} points, why use {topic}?",
                    "In the data table below with {m} samples, what’s {topic}’s assumption?",
                    "What’s the simplest way {topic} handles binary {input}?",
                    "Given the line graph below, how does {topic} estimate likelihoods?",
                    "How does {topic} use presence/absence in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {application}?",
                    "What does {topic} assume about {feature} in {context}?"
                ],
                "medium": [
                    "Derive the Bernoulli probability for presence={y} in {topic} with p={p}.",
                    "Based on the scatter plot below with {n} points, how does {topic} classify?",
                    "In the line graph below, how does {topic} model binary probabilities?",
                    "Given the data table below with {m} samples, calculate {topic}’s likelihood.",
                    "How does {topic} estimate probabilities for {f} binary features?",
                    "Based on the scatter plot below, why does {topic} fit binary data?",
                    "In the data table below, derive {topic}’s prediction for {feature}.",
                    "Calculate the likelihood for {feature} presence in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} in binaries?",
                    "How does {topic} use absence in the scatter plot below?",
                    "Based on the data table below, why does {topic} excel in {scenario}?",
                    "In the line graph below with slope {s}, what does it imply for {topic}?",
                    "Given the scatter plot below, how does {topic} adjust probabilities?",
                    "Why does {topic} model {feature} as Bernoulli in the data table below?"
                ],
                "hard": [
                    "Prove why Bernoulli assumptions work for {topic}’s {task}.",
                    "Analyze {topic}’s classification in the scatter plot below with {n} points.",
                    "Derive the full Bernoulli model for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise}?",
                    "Critique {topic}’s binary assumption using the line graph below.",
                    "Prove the likelihood’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s Bernoulli probability.",
                    "In the line graph below, how does {topic} adapt binaries for {task}?",
                    "Analyze {topic}’s presence estimation in the scatter plot below.",
                    "Prove why {topic} excels for binary data in the data table below.",
                    "Given the line graph below, critique {topic}’s Bernoulli fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} sparsity?",
                    "Derive {topic}’s Bernoulli posterior in the data table below.",
                    "Critique {topic}’s Bernoulli approach in the line graph below."
                ]
            },
            "Implementation": {
                "easy": [
                    "What Python library is used to implement {topic}?",
                    "How does {topic}’s fit method work in {context}?",
                    "Based on the scatter plot below, how does {topic} predict {n} points?",
                    "Calculate the prediction for x={x} in {topic} with p={p}.",
                    "In the line graph below, what does {topic}’s output represent?",
                    "Given the data table below with {m} samples, how does {topic} train?",
                    "What’s the role of scikit-learn in {topic}’s {task}?",
                    "Based on the scatter plot below, why does {topic} classify easily?",
                    "In the data table below, how does {topic} use {feature} for prediction?",
                    "How does {topic} compute probabilities in {scenario}?",
                    "Given the line graph below, what does {topic}’s curve predict?",
                    "What’s the simplest way to implement {topic} for {n} points?",
                    "Based on the scatter plot below, how does {topic} handle {output}?",
                    "How does {topic} process {input} in the data table below?"
                ],
                "medium": [
                    "Explain how scikit-learn trains {topic} for {n} samples in the scatter plot below.",
                    "If probability p={p}, compute the output for x={x} in {topic}.",
                    "Based on the line graph below, how does {topic} predict probabilities?",
                    "Given the data table below with {m} samples, how does {topic} fit the data?",
                    "In the scatter plot below, how does {topic}’s predict method work for {n} points?",
                    "Derive {topic}’s prediction rule for {f} features in the data table below.",
                    "Based on the line graph below, why does {topic}’s output stabilize?",
                    "Given the scatter plot below, how does {topic} handle {feature} in {scenario}?",
                    "In the data table below, how does {topic} compute {output} with p={p}?",
                    "How does {topic}’s predict_proba work for P(y=1)={p} in {context}?",
                    "Based on the line graph below with slope {s}, what does {topic} predict?",
                    "Given the scatter plot below, why is {topic} efficient for {task}?",
                    "In the data table below, how does {topic} adjust {parameter}?",
                    "How does {topic} implement {method} in the scatter plot below?"
                ],
                "hard": [
                    "Prove how scikit-learn optimizes {topic}’s {parameter} in {t} iterations.",
                    "Analyze {topic}’s runtime for {n} samples in the scatter plot below.",
                    "Derive the full prediction equation for {topic} with p={p} in the data table below.",
                    "In the line graph below, critique {topic}’s implementation for {scenario}.",
                    "Based on the scatter plot below, how does {topic} scale with {f} features?",
                    "Given the data table below with {m} samples, prove {topic}’s efficiency.",
                    "Critique manual versus scikit-learn implementation of {topic} in the line graph below.",
                    "In the scatter plot below with {n} points, how does {topic} handle {noise}?",
                    "Derive {topic}’s probability distribution for {n} classes in the data table below.",
                    "Based on the line graph below, analyze {topic}’s convergence for {task}.",
                    "Prove {topic}’s prediction accuracy in the scatter plot below with p={p}.",
                    "Given the data table below, how does {topic} optimize {feature} probabilities?",
                    "Critique {topic}’s implementation trade-offs in the line graph below.",
                    "Analyze {topic}’s performance for {problem} in the data table below."
                ]
            }
        }
    }
}