random_forest_templates = {
    "Random Forest": {
        "subtopics": {
            "Introduction": {
                "easy": [
                    "What is the main concept of {topic} in {application}?",
                    "How does {topic} differ from {model} in terms of {aspect}?",
                    "Based on the scatter plot below with {n} points, would {topic} work well? Why?",
                    "Why is {topic} effective for {scenario} in {field}?",
                    "In the line graph below of ensemble predictions, what does the trend suggest?",
                    "What advantage does {topic} have over {alternative} for {task}?",
                    "Given the data table below with {m} samples, is {topic} suitable? Why?",
                    "How does {topic} classify {output} in a {context} scenario?",
                    "Based on the scatter plot below, why is {topic} a good fit for {application}?",
                    "What’s the role of multiple trees in {topic}?",
                    "In the data table below, how does {topic} use {feature} patterns?",
                    "Why might {topic} be chosen for {goal} over {model}?",
                    "Based on the line graph below, what shows {topic}’s strength?",
                    "How does {topic} improve {task} in {scenario}?"
                ],
                "medium": [
                    "Compare {topic} and {model} for {task} based on {dimension}.",
                    "Based on the scatter plot below with {n} points, why prefer {topic}?",
                    "In the line graph below with slope {s}, why is {topic} effective for {goal}?",
                    "Given the data table below with {m} samples, how does {topic} aggregate {feature}?",
                    "Why does {topic} perform well in {scenario} compared to {alternative}?",
                    "If the scatter plot below shows {n} points, how does {topic} ensemble them?",
                    "Based on the line graph below, what does the voting trend imply?",
                    "In a {application} context, why does {topic} fit the data table below?",
                    "Contrast {topic} and {alternative} for {task} using the scatter plot below.",
                    "Given the data table below, why is {topic} ideal for {output} prediction?",
                    "How does {topic} balance {dimension} and {aspect} in {scenario}?",
                    "Based on the scatter plot below, why is {topic} suited for {field}?",
                    "In the line graph below, what does the ensemble trend suggest?",
                    "Why might {topic} struggle with {problem} in the data table below?"
                ],
                "hard": [
                    "Analyze why {topic} outperforms {alternative} for {goal} in {context}.",
                    "Based on the scatter plot below with {t} trees, why is {topic}’s approach effective?",
                    "Critique {topic} versus {model} for {problem} using the line graph below.",
                    "In the data table below with {m} samples, why prefer {topic} over {alternative}?",
                    "Given the scatter plot below, explain {topic}’s suitability for {task}.",
                    "If the line graph below shows noise {p}, how does {topic} adjust?",
                    "Analyze the data table below: how does {topic} handle {feature} variance?",
                    "Based on the scatter plot below with {n} points, critique {topic}’s ensemble.",
                    "In the line graph below over {t} trees, what indicates {topic}’s performance?",
                    "Why does {topic} excel in {scenario} but struggle with {problem} in the data below?",
                    "Given the scatter plot below, prove {topic}’s effectiveness for {field}.",
                    "How does {topic} mitigate {noise} in the data table below?",
                    "Critique {topic}’s ensemble approach based on the line graph below.",
                    "Based on the data table below, justify {topic}’s use in {application}."
                ]
            },
            "Bootstrap Aggregation": {
                "easy": [
                    "What is bootstrap aggregation in {topic}?",
                    "How does {topic} sample data with replacement?",
                    "Based on the scatter plot below, how does {topic} use bagging for {n} points?",
                    "What’s the role of bagging in {topic} for {task}?",
                    "In the line graph below, what does the bagged trend show?",
                    "Given the data table below, how does {topic} apply bootstrap?",
                    "How does {topic} reduce variance with bagging?",
                    "Based on the scatter plot below with {n} points, why use bagging?",
                    "In the data table below with {m} samples, what’s bagging’s effect?",
                    "What’s the simplest explanation of bagging in {topic}?",
                    "Given the line graph below, how does {topic} aggregate samples?",
                    "How does {topic} use bagging on {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need bootstrap?",
                    "What does sampling with replacement mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how bagging improves {topic}’s accuracy in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} sample data?",
                    "In the line graph below, how does {topic} reduce variance with bagging?",
                    "Given the data table below with {m} samples, how does {topic} apply bootstrap?",
                    "How does {topic} balance bias and variance with bagging for {f} features?",
                    "Based on the scatter plot below, why does {topic} rely on bagging for {problem}?",
                    "In the data table below, derive {topic}’s bagged prediction for {feature}.",
                    "Calculate the bagged sample size for {t} trees in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with bagging?",
                    "How does {topic} use bootstrap in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with bagging?",
                    "In the line graph below with slope {s}, what does bagging imply?",
                    "Given the scatter plot below, how does {topic} adjust bagging?",
                    "Why does {topic} rely on bagging in the data table below?"
                ],
                "hard": [
                    "Prove why bagging reduces variance in {topic}’s {task}.",
                    "Analyze {topic}’s bootstrap aggregation in the scatter plot below with {n} points.",
                    "Derive the full bagging process for {topic} with {t} trees.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with bagging?",
                    "Critique bagging’s impact in {topic} using the line graph below.",
                    "Prove bagging’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s bagged decision rule.",
                    "In the line graph below, how does {topic} adapt bagging for {task}?",
                    "Analyze {topic}’s variance reduction in the scatter plot below.",
                    "Prove why {topic} excels with bagging in the data table below.",
                    "Given the line graph below, critique {topic}’s bagging for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with bagging?",
                    "Derive {topic}’s bootstrap optimization in the data table below.",
                    "Critique {topic}’s bagging efficiency in the line graph below."
                ]
            },
            "Feature Randomness": {
                "easy": [
                    "What is feature randomness in {topic}?",
                    "How does {topic} select random features?",
                    "Based on the scatter plot below, how does {topic} use randomness for {n} points?",
                    "What’s the role of feature selection in {topic} for {task}?",
                    "In the line graph below, what does the random trend show?",
                    "Given the data table below, how does {topic} apply feature randomness?",
                    "How does {topic} increase diversity with randomness?",
                    "Based on the scatter plot below with {n} points, why use random features?",
                    "In the data table below with {m} samples, what’s randomness’s effect?",
                    "What’s the simplest explanation of feature randomness in {topic}?",
                    "Given the line graph below, how does {topic} pick features?",
                    "How does {topic} use randomness on {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need feature randomness?",
                    "What does random selection mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how feature randomness improves {topic}’s accuracy in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} select features?",
                    "In the line graph below, how does {topic} diversify with randomness?",
                    "Given the data table below with {m} samples, how does {topic} apply random splits?",
                    "How does {topic} balance feature subsets for {f} features?",
                    "Based on the scatter plot below, why does {topic} rely on randomness for {problem}?",
                    "In the data table below, derive {topic}’s random feature prediction.",
                    "Calculate the feature subset size for {t} trees in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with randomness?",
                    "How does {topic} use random features in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with randomness?",
                    "In the line graph below with slope {s}, what does randomness imply?",
                    "Given the scatter plot below, how does {topic} adjust feature selection?",
                    "Why does {topic} rely on randomness in the data table below?"
                ],
                "hard": [
                    "Prove why feature randomness enhances {topic}’s {task}.",
                    "Analyze {topic}’s feature randomness in the scatter plot below with {n} points.",
                    "Derive the full randomness process for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with randomness?",
                    "Critique randomness’s impact in {topic} using the line graph below.",
                    "Prove randomness’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s random feature decision.",
                    "In the line graph below, how does {topic} adapt randomness for {task}?",
                    "Analyze {topic}’s diversity gain in the scatter plot below.",
                    "Prove why {topic} excels with random features in the data table below.",
                    "Given the line graph below, critique {topic}’s randomness for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with randomness?",
                    "Derive {topic}’s feature subset optimization in the data table below.",
                    "Critique {topic}’s randomness efficiency in the line graph below."
                ]
            },
            "Voting and Averaging": {
                "easy": [
                    "What is the purpose of voting in {topic}?",
                    "How does {topic} average predictions?",
                    "Based on the scatter plot below, how does {topic} classify {n} points?",
                    "What’s the role of majority voting in {topic} for {task}?",
                    "In the line graph below, what does the voting trend show?",
                    "Given the data table below, how does {topic} combine predictions?",
                    "How does {topic} use averaging for regression?",
                    "Based on the scatter plot below with {n} points, why use voting?",
                    "In the data table below with {m} samples, what’s voting’s effect?",
                    "What’s the simplest way to combine predictions in {topic}?",
                    "Given the line graph below, how does {topic} aggregate trees?",
                    "How does {topic} vote on {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need voting?",
                    "What does averaging mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how majority voting improves {topic}’s accuracy in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} average predictions?",
                    "In the line graph below, how does {topic} combine tree outputs?",
                    "Given the data table below with {m} samples, how does {topic} vote on {feature}?",
                    "How does {topic} balance voting and averaging for {f} features?",
                    "Based on the scatter plot below, why does {topic} rely on voting for {problem}?",
                    "In the data table below, derive {topic}’s voted prediction for {feature}.",
                    "Calculate the averaged output for {t} trees in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with voting?",
                    "How does {topic} use majority voting in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with averaging?",
                    "In the line graph below with slope {s}, what does voting imply?",
                    "Given the scatter plot below, how does {topic} adjust averaging?",
                    "Why does {topic} rely on voting in the data table below?"
                ],
                "hard": [
                    "Prove why voting optimizes {topic}’s {task}.",
                    "Analyze {topic}’s voting in the scatter plot below with {n} points.",
                    "Derive the full averaging process for {topic} with {t} trees.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with voting?",
                    "Critique voting versus averaging in {topic} using the line graph below.",
                    "Prove voting’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s combined prediction.",
                    "In the line graph below, how does {topic} adapt voting for {task}?",
                    "Analyze {topic}’s prediction stability in the scatter plot below.",
                    "Prove why {topic} excels with averaging in the data table below.",
                    "Given the line graph below, critique {topic}’s voting for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with voting?",
                    "Derive {topic}’s voting optimization in the data table below.",
                    "Critique {topic}’s voting efficiency in the line graph below."
                ]
            },
            "Hyperparameters": {
                "easy": [
                    "What is the role of hyperparameters in {topic}?",
                    "How does {topic} set the number of trees?",
                    "Based on the scatter plot below, how does {t} trees affect {topic}?",
                    "What’s the purpose of max_depth in {topic} for {task}?",
                    "In the line graph below, what does the hyperparameter trend show?",
                    "Given the data table below, how does {topic} tune hyperparameters?",
                    "How does {topic} use feature subset size?",
                    "Based on the scatter plot below with {n} points, why tune {t} trees?",
                    "In the data table below with {m} samples, what’s the effect of depth?",
                    "What’s the simplest way to set hyperparameters in {topic}?",
                    "Given the line graph below, how does {topic} adjust {t} trees?",
                    "How does {topic} tune {feature} splits in the scatter plot below?",
                    "Based on the data table below, why does {topic} need hyperparameters?",
                    "What does n_estimators mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how {t} trees improve {topic}’s accuracy in the scatter plot below.",
                    "Based on the scatter plot below with {n} points, how does {topic} set max_depth?",
                    "In the line graph below, how does {topic} adjust with feature subset size?",
                    "Given the data table below with {m} samples, how does {topic} tune {t} trees?",
                    "How does {topic} balance hyperparameters for {f} features?",
                    "Based on the scatter plot below, why does {topic} need a specific {t} for {problem}?",
                    "In the data table below, derive {topic}’s hyperparameter effect on {feature}.",
                    "Calculate the impact of depth={t} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with hyperparameters?",
                    "How does {topic} adjust n_estimators in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with tuning?",
                    "In the line graph below with slope {s}, what does tuning imply?",
                    "Given the scatter plot below, how does {topic} optimize hyperparameters?",
                    "Why does {topic} rely on hyperparameters in the data table below?"
                ],
                "hard": [
                    "Prove why {t} trees optimize {topic}’s {task}.",
                    "Analyze {topic}’s hyperparameters in the scatter plot below with {n} points.",
                    "Derive the full hyperparameter tuning process for {topic} with {f} features.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with tuning?",
                    "Critique depth versus n_estimators in {topic} using the line graph below.",
                    "Prove hyperparameters’ role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s optimal hyperparameter settings.",
                    "In the line graph below, how does {topic} adapt tuning for {task}?",
                    "Analyze {topic}’s sensitivity to hyperparameters in the scatter plot below.",
                    "Prove why {topic} excels with tuned trees in the data table below.",
                    "Given the line graph below, critique {topic}’s tuning for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with n_estimators?",
                    "Derive {topic}’s hyperparameter optimization in the data table below.",
                    "Critique {topic}’s hyperparameter trade-offs in the line graph below."
                ]
            },
            "Implementation": {
                "easy": [
                    "What Python library is used to implement {topic}?",
                    "How does {topic}’s fit method work in {context}?",
                    "Based on the scatter plot below, how does {topic} predict {n} points?",
                    "Calculate the prediction for {t} trees in {topic}.",
                    "In the line graph below, what does {topic}’s ensemble represent?",
                    "Given the data table below with {m} samples, how does {topic} train?",
                    "What’s the role of scikit-learn in {topic}’s {task}?",
                    "Based on the scatter plot below, why does {topic} classify easily?",
                    "In the data table below, how does {topic} use {feature} for prediction?",
                    "How does {topic} build an ensemble in {scenario}?",
                    "Given the line graph below, what does {topic}’s curve predict?",
                    "What’s the simplest way to implement {topic} for {n} points?",
                    "Based on the scatter plot below, how does {topic} handle {output}?",
                    "How does {topic} process {input} in the data table below?"
                ],
                "medium": [
                    "Explain how scikit-learn trains {topic} for {n} samples in the scatter plot below.",
                    "If n_estimators={t}, compute the ensemble output for {topic}.",
                    "Based on the line graph below, how does {topic} predict outcomes?",
                    "Given the data table below with {m} samples, how does {topic} fit the data?",
                    "In the scatter plot below, how does {topic}’s predict method work for {n} points?",
                    "Derive {topic}’s ensemble structure for {f} features in the data table below.",
                    "Based on the line graph below, why does {topic}’s ensemble stabilize?",
                    "Given the scatter plot below, how does {topic} handle {feature} in {scenario}?",
                    "In the data table below, how does {topic} compute {output} with {t} trees?",
                    "How does {topic}’s max_features parameter work in {context}?",
                    "Based on the line graph below with slope {s}, what does {topic} predict?",
                    "Given the scatter plot below, why is {topic} efficient for {task}?",
                    "In the data table below, how does {topic} adjust {parameter}?",
                    "How does {topic} implement {method} in the scatter plot below?"
                ],
                "hard": [
                    "Prove how scikit-learn optimizes {topic}’s {parameter} in {t} trees.",
                    "Analyze {topic}’s runtime for {n} samples in the scatter plot below.",
                    "Derive the full ensemble equation for {topic} in the data table below.",
                    "In the line graph below, critique {topic}’s implementation for {scenario}.",
                    "Based on the scatter plot below, how does {topic} scale with {f} features?",
                    "Given the data table below with {m} samples, prove {topic}’s efficiency.",
                    "Critique manual versus scikit-learn implementation of {topic} in the line graph below.",
                    "In the scatter plot below with {n} points, how does {topic} handle {noise}?",
                    "Derive {topic}’s voting computation for {n} points in the data table below.",
                    "Based on the line graph below, analyze {topic}’s convergence for {task}.",
                    "Prove {topic}’s prediction accuracy in the scatter plot below with {t} trees.",
                    "Given the data table below, how does {topic} optimize {feature} ensemble?",
                    "Critique {topic}’s implementation trade-offs in the line graph below.",
                    "Analyze {topic}’s performance for {problem} in the data table below."
                ]
            }
        }
    }
}