svm_templates = {
    "Support Vector Machines": {
        "subtopics": {
            "Introduction": {
                "easy": [
                    "What is the core idea of {topic} in {application}?",
                    "How does {topic} differ from {model} in terms of {aspect}?",
                    "Based on the scatter plot below with {n} points, would {topic} work well? Why?",
                    "Why is {topic} effective for {scenario} in {field}?",
                    "In the line graph below of decision boundary, what does the separation suggest?",
                    "What advantage does {topic} have over {alternative} for {task}?",
                    "Given the data table below with {m} samples, is {topic} suitable? Why?",
                    "How does {topic} classify {output} in a {context} scenario?",
                    "Based on the scatter plot below, why is {topic} a good fit for {application}?",
                    "What’s the main goal of maximizing the margin in {topic}?",
                    "In the data table below, how does {topic} use {feature} patterns?",
                    "Why might {topic} be chosen for {goal} over {model}?",
                    "Based on the line graph below, what trend shows {topic}’s strength?",
                    "How does {topic} simplify {task} in {scenario}?"
                ],
                "medium": [
                    "Compare {topic} and {model} for {task} based on {dimension}.",
                    "Based on the scatter plot below with {n} points, why prefer {topic}?",
                    "In the line graph below with slope {s}, why is {topic} effective for {goal}?",
                    "Given the data table below with {m} samples, how does {topic} separate {feature}?",
                    "Why does {topic} perform well in {scenario} compared to {alternative}?",
                    "If the scatter plot below shows {n} points, how does {topic} define the margin?",
                    "Based on the line graph below, what does the boundary trend imply?",
                    "In a {application} context, why does {topic} fit the data table below?",
                    "Contrast {topic} and {alternative} for {task} using the scatter plot below.",
                    "Given the data table below, why is {topic} ideal for {output} prediction?",
                    "How does {topic} balance {dimension} and {aspect} in {scenario}?",
                    "Based on the scatter plot below, why is {topic} suited for {field}?",
                    "In the line graph below, what does the margin width suggest about {topic}?",
                    "Why might {topic} struggle with {problem} in the data table below?"
                ],
                "hard": [
                    "Analyze why {topic} outperforms {alternative} for {goal} in {context}.",
                    "Based on the scatter plot below with w={w}, why is {topic}’s margin optimal?",
                    "Critique {topic} versus {model} for {problem} using the line graph below.",
                    "In the data table below with {m} samples, why prefer {topic} over {alternative}?",
                    "Given the scatter plot below, explain {topic}’s suitability for {task}.",
                    "If the line graph below shows noise {p}, how does {topic} adjust?",
                    "Analyze the data table below: how does {topic} handle {feature} variance?",
                    "Based on the scatter plot below with {n} points, critique {topic}’s margin.",
                    "In the line graph below over {t} iterations, what indicates {topic}’s convergence?",
                    "Why does {topic} excel in {scenario} but struggle with {problem} in the data below?",
                    "Given the scatter plot below, prove {topic}’s effectiveness for {field}.",
                    "How does {topic} mitigate {noise} in the data table below?",
                    "Critique {topic}’s margin maximization based on the line graph below.",
                    "Based on the data table below, justify {topic}’s use in {application}."
                ]
            },
            "Linear SVM": {
                "easy": [
                    "What is the goal of a linear {topic} for {task}?",
                    "How does a hard margin work in {topic}?",
                    "Based on the scatter plot below, is {topic} suitable for {n} points?",
                    "What’s the role of the margin in {topic} for {output}?",
                    "In the line graph below, what does the linear boundary show?",
                    "Given the data table below, how does {topic} separate classes?",
                    "How does a soft margin differ from a hard margin in {topic}?",
                    "Based on the scatter plot below with {n} points, why use {topic}?",
                    "In the data table below with {m} samples, what’s the linear assumption?",
                    "What’s the simplest explanation of a linear {topic}?",
                    "Given the line graph below, how does {topic} classify {output}?",
                    "How does {topic} use {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need separability?",
                    "What does a linear boundary mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how {topic} finds the optimal hyperplane for {n} points in the scatter plot below.",
                    "Based on the scatter plot below with w={w}, how does {topic} set the margin?",
                    "In the line graph below, how does a soft margin adjust {topic}’s boundary?",
                    "Given the data table below with {m} samples, how does {topic} handle misclassifications?",
                    "How does {topic} balance margin size and errors in {scenario}?",
                    "Based on the scatter plot below, why does {topic} prefer linear separability?",
                    "In the data table below, derive {topic}’s hyperplane for {feature}.",
                    "Calculate the margin width for w={w} in {topic}.",
                    "Given the line graph below, how does {topic} adapt to {noise}?",
                    "How does {topic} use a soft margin in the scatter plot below?",
                    "Based on the data table below, why does {topic} suit {goal}?",
                    "In the line graph below with slope {s}, what does it imply for {topic}?",
                    "Given the scatter plot below, how does {topic} adjust the boundary?",
                    "Why does {topic} rely on linearity in the data table below?"
                ],
                "hard": [
                    "Prove why a hard margin maximizes separation in {topic} for {task}.",
                    "Analyze {topic}’s soft margin in the scatter plot below with {n} points.",
                    "Derive the hyperplane equation for {topic} with w={w}, b={b}.",
                    "In the data table below with {m} samples, how does {topic} handle {noise}?",
                    "Critique hard versus soft margins in {topic} using the line graph below.",
                    "Prove the margin’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s linear decision rule.",
                    "In the line graph below, how does {topic} adapt the boundary for {task}?",
                    "Analyze {topic}’s separability assumption in the scatter plot below.",
                    "Prove why {topic} excels for linear data in the data table below.",
                    "Given the line graph below, critique {topic}’s linear fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} overlap?",
                    "Derive {topic}’s soft margin optimization in the data table below.",
                    "Critique {topic}’s linearity in the line graph below."
                ]
            },
            "Kernel Trick": {
                "easy": [
                    "What is the purpose of the kernel trick in {topic}?",
                    "How does an RBF kernel work in {topic}?",
                    "Based on the scatter plot below, how does {topic} classify {n} points?",
                    "What’s the role of a polynomial kernel in {topic} for {task}?",
                    "In the line graph below, what does the transformed boundary show?",
                    "Given the data table below, how does {topic} handle non-linear data?",
                    "How does {topic} use kernels to improve {output}?",
                    "Based on the scatter plot below with {n} points, why use a kernel?",
                    "In the data table below with {m} samples, what’s the kernel’s effect?",
                    "What’s the simplest explanation of the kernel trick in {topic}?",
                    "Given the line graph below, how does {topic} map {feature}?",
                    "How does {topic} apply a kernel in the scatter plot below?",
                    "Based on the data table below, why does {topic} need kernels?",
                    "What does a kernel do in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how an RBF kernel transforms {n} points in the scatter plot below.",
                    "Based on the scatter plot below with w={w}, how does {topic} use a polynomial kernel?",
                    "In the line graph below, how does {topic} adjust with a kernel?",
                    "Given the data table below with {m} samples, how does {topic} classify non-linearly?",
                    "How does {topic} choose between RBF and polynomial kernels for {scenario}?",
                    "Based on the scatter plot below, why does {topic} need a kernel for {problem}?",
                    "In the data table below, derive {topic}’s kernel transformation for {feature}.",
                    "Calculate the kernel value for x1={x}, x2={x} with gamma={g} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with kernels?",
                    "How does {topic} apply an RBF kernel in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with kernels?",
                    "In the line graph below with slope {s}, what does the kernel imply?",
                    "Given the scatter plot below, how does {topic} adjust with a polynomial kernel?",
                    "Why does {topic} rely on kernels in the data table below?"
                ],
                "hard": [
                    "Prove why the kernel trick enables {topic} for {task} in non-linear data.",
                    "Analyze {topic}’s RBF kernel in the scatter plot below with {n} points.",
                    "Derive the kernel function for {topic} with degree={k} and gamma={g}.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with kernels?",
                    "Critique RBF versus polynomial kernels in {topic} using the line graph below.",
                    "Prove the kernel’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s transformed decision rule.",
                    "In the line graph below, how does {topic} adapt kernels for {task}?",
                    "Analyze {topic}’s kernel transformation in the scatter plot below.",
                    "Prove why {topic} excels with kernels in the data table below.",
                    "Given the line graph below, critique {topic}’s kernel fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} complexity?",
                    "Derive {topic}’s kernel-based margin in the data table below.",
                    "Critique {topic}’s kernel approach in the line graph below."
                ]
            },
            "Mathematical Foundation": {
                "easy": [
                    "What are support vectors in {topic} and their role in {task}?",
                    "How does {topic} use Lagrange multipliers?",
                    "Based on the scatter plot below, what do support vectors do?",
                    "What’s the dual form in {topic} for {output}?",
                    "In the line graph below, what does the margin width represent?",
                    "Given the data table below, how does {topic} identify support vectors?",
                    "How does {topic} optimize the margin mathematically?",
                    "Based on the scatter plot below with {n} points, why use support vectors?",
                    "In the data table below with {m} samples, what’s the dual problem?",
                    "What’s the simplest explanation of {topic}’s math?",
                    "Given the line graph below, how does {topic} define the boundary?",
                    "How does {topic} use {feature} in the scatter plot below mathematically?",
                    "Based on the data table below, why does {topic} rely on support vectors?",
                    "What does the primal form mean in {topic}’s {context}?"
                ],
                "medium": [
                    "Derive the dual form of {topic} for {n} points in the scatter plot below.",
                    "Based on the scatter plot below with w={w}, how does {topic} use Lagrange multipliers?",
                    "In the line graph below, how does {topic} optimize the margin?",
                    "Given the data table below with {m} samples, calculate {topic}’s support vectors.",
                    "How does {topic} solve the primal problem for {f} features?",
                    "Based on the scatter plot below, why does {topic} depend on support vectors?",
                    "In the data table below, derive {topic}’s dual objective for {feature}.",
                    "Calculate the margin distance for w={w}, b={b} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} mathematically?",
                    "How does {topic} use the dual form in the scatter plot below?",
                    "Based on the data table below, why does {topic} optimize {goal}?",
                    "In the line graph below with slope {s}, what does it imply mathematically?",
                    "Given the scatter plot below, how does {topic} adjust support vectors?",
                    "Why does {topic} use Lagrange multipliers in the data table below?"
                ],
                "hard": [
                    "Prove the optimality of support vectors in {topic} for {task}.",
                    "Analyze {topic}’s dual form in the scatter plot below with {n} points.",
                    "Derive the full Lagrangian for {topic} with w={w}, b={b}.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} mathematically?",
                    "Critique primal versus dual forms in {topic} using the line graph below.",
                    "Prove the margin’s maximization in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s support vector conditions.",
                    "In the line graph below, how does {topic} adapt the dual for {task}?",
                    "Analyze {topic}’s mathematical complexity in the scatter plot below.",
                    "Prove why {topic} relies on support vectors in the data table below.",
                    "Given the line graph below, critique {topic}’s math for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} in the dual?",
                    "Derive {topic}’s KKT conditions in the data table below.",
                    "Critique {topic}’s mathematical foundation in the line graph below."
                ]
            },
            "Regularization and Cost": {
                "easy": [
                    "What is the role of the C parameter in {topic}?",
                    "How does {topic} balance margin and errors?",
                    "Based on the scatter plot below, how does C affect {topic}?",
                    "What’s the cost function in {topic} for {task}?",
                    "In the line graph below, what does the cost trend show?",
                    "Given the data table below, how does {topic} use regularization?",
                    "How does a large C differ from a small C in {topic}?",
                    "Based on the scatter plot below with {n} points, why use C?",
                    "In the data table below with {m} samples, what’s C’s effect?",
                    "What’s the simplest explanation of regularization in {topic}?",
                    "Given the line graph below, how does {topic} adjust errors?",
                    "How does {topic} apply C to {feature} in the scatter plot below?",
                    "Based on the data table below, why does {topic} need regularization?",
                    "What does the cost penalize in {topic}’s {context}?"
                ],
                "medium": [
                    "Explain how C={c} changes {topic}’s margin in the scatter plot below.",
                    "Based on the scatter plot below with w={w}, how does {topic} use regularization?",
                    "In the line graph below, how does {topic} adjust cost with C={c}?",
                    "Given the data table below with {m} samples, how does {topic} tune C?",
                    "How does {topic} trade off margin and errors for {scenario}?",
                    "Based on the scatter plot below, why does {topic} need a small C for {problem}?",
                    "In the data table below, derive {topic}’s cost function for {feature}.",
                    "Calculate the regularized cost for C={c}, w={w} in {topic}.",
                    "Given the line graph below, how does {topic} handle {noise} with regularization?",
                    "How does {topic} adjust the margin with C in the scatter plot below?",
                    "Based on the data table below, why does {topic} improve {goal} with C?",
                    "In the line graph below with slope {s}, what does C imply?",
                    "Given the scatter plot below, how does {topic} balance errors?",
                    "Why does {topic} use regularization in the data table below?"
                ],
                "hard": [
                    "Prove why C controls regularization in {topic} for {task}.",
                    "Analyze {topic}’s cost function in the scatter plot below with {n} points.",
                    "Derive the full cost with C={c} for {topic} with w={w}.",
                    "In the data table below with {m} samples, how does {topic} handle {noise} with C?",
                    "Critique large versus small C in {topic} using the line graph below.",
                    "Prove the cost’s role in {topic} based on the scatter plot below.",
                    "Based on the data table below, derive {topic}’s regularized margin.",
                    "In the line graph below, how does {topic} adapt C for {task}?",
                    "Analyze {topic}’s regularization impact in the scatter plot below.",
                    "Prove why {topic} balances errors with C in the data table below.",
                    "Given the line graph below, critique {topic}’s cost fit for {problem}.",
                    "Based on the scatter plot below, how does {topic} handle {feature} with C?",
                    "Derive {topic}’s cost optimization in the data table below.",
                    "Critique {topic}’s regularization trade-offs in the line graph below."
                ]
            },
            "Implementation": {
                "easy": [
                    "What Python library is used to implement {topic}?",
                    "How does {topic}’s fit method work in {context}?",
                    "Based on the scatter plot below, how does {topic} predict {n} points?",
                    "Calculate the prediction for w={w}, x={x} in {topic}.",
                    "In the line graph below, what does {topic}’s boundary represent?",
                    "Given the data table below with {m} samples, how does {topic} train?",
                    "What’s the role of scikit-learn in {topic}’s {task}?",
                    "Based on the scatter plot below, why does {topic} classify easily?",
                    "In the data table below, how does {topic} use {feature} for prediction?",
                    "How does {topic} compute the margin in {scenario}?",
                    "Given the line graph below, what does {topic}’s curve predict?",
                    "What’s the simplest way to implement {topic} for {n} points?",
                    "Based on the scatter plot below, how does {topic} handle {output}?",
                    "How does {topic} process {input} in the data table below?"
                ],
                "medium": [
                    "Explain how scikit-learn trains {topic} for {n} samples in the scatter plot below.",
                    "If weights are w1={w1}, w2={w2}, compute the output for x1={x}, x2={x} in {topic}.",
                    "Based on the line graph below, how does {topic} predict the boundary?",
                    "Given the data table below with {m} samples, how does {topic} fit the data?",
                    "In the scatter plot below, how does {topic}’s predict method work for {n} points?",
                    "Derive {topic}’s decision rule for {f} features in the data table below.",
                    "Based on the line graph below, why does {topic}’s margin stabilize?",
                    "Given the scatter plot below, how does {topic} handle {feature} in {scenario}?",
                    "In the data table below, how does {topic} compute {output} with w={w}?",
                    "How does {topic}’s kernel parameter work for C={c} in {context}?",
                    "Based on the line graph below with slope {s}, what does {topic} predict?",
                    "Given the scatter plot below, why is {topic} efficient for {task}?",
                    "In the data table below, how does {topic} adjust {parameter}?",
                    "How does {topic} implement {method} in the scatter plot below?"
                ],
                "hard": [
                    "Prove how scikit-learn optimizes {topic}’s {parameter} in {t} iterations.",
                    "Analyze {topic}’s runtime for {n} samples in the scatter plot below.",
                    "Derive the full prediction equation for {topic} with w={w} in the data table below.",
                    "In the line graph below, critique {topic}’s implementation for {scenario}.",
                    "Based on the scatter plot below, how does {topic} scale with {f} features?",
                    "Given the data table below with {m} samples, prove {topic}’s efficiency.",
                    "Critique manual versus scikit-learn implementation of {topic} in the line graph below.",
                    "In the scatter plot below with {n} points, how does {topic} handle {noise}?",
                    "Derive {topic}’s kernel transformation for {n} points in the data table below.",
                    "Based on the line graph below, analyze {topic}’s convergence for {task}.",
                    "Prove {topic}’s prediction accuracy in the scatter plot below with w={w}.",
                    "Given the data table below, how does {topic} optimize {feature} weights?",
                    "Critique {topic}’s implementation trade-offs in the line graph below.",
                    "Analyze {topic}’s performance for {problem} in the data table below."
                ]
            }
        }
    }
}